/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaGrafica;

import CapaException.BDException;
import CapaException.PersonaException;
import CapaLogica.FachadaPersona;
import CapaLogica.InasistenciaDocente;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Ingreso extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;
    FachadaPersona fachadaper = new FachadaPersona();

    /**
     * Creates new form Ingreso
     */
    public Ingreso() {
        initComponents();
        //Lo castea a DefaultTableModel para poder usar métodos como addRow, setRowCount, etc.
        modeloTabla = (DefaultTableModel) Tabla.getModel(); //Pide a la tabla su modelo actual.
    }
//String[] columnas = {...};Encabezados de las columnas de la tabla.
//modeloTabla = new DefaultTableModel(null, columnas) { ... };
//un DefaultTableModel sin filas (null = 0 filas) y con esos encabezados.
//Se crea una subclase anónima que sobreescribe isCellEditable(...) devolviendo false → todas las 
    //celdas no editables desde la interfaz.Tabla.setModel(modeloTabla); → Conecta el modelo recién 
    //creado a la JTable. Desde ahora la vista y tu variable modeloTabla apuntan al mismo objeto.
//Detalle: pasar null como datos iniciales es equivalente a empezar con 0 filas; siempre conservarás 
    //los encabezados.    
    private void configurarTabla() {
        String[] columnas = {"CI", "Nombre", "Apellido","Tareas"};
        modeloTabla = new DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        Tabla.setModel(modeloTabla);
    }

    private void limpiarCamposYTabla() {
        txtFechaInicio.setText("");
        txtFechaFin.setText("");
        txtMotivo.setText("");
        if (modeloTabla == null) { // rescata el modelo desde la tabla si hace falta
            modeloTabla = (DefaultTableModel) Tabla.getModel();
        }
        modeloTabla.setRowCount(0);//Deja el modelo con 0 filas (vacía la tabla) sin perder los encabezados. 
        //Es la forma más simple de limpiar.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txtTareas1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTurno = new javax.swing.JTextField();
        txtGrupo = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso");

        jLabel1.setText("Ingresar Datos");

        jLabel2.setText("Ci ");

        jLabel3.setText("Fecha Inicio");

        jLabel4.setText("Fecha Fin");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ci", "Fecha Inicio", "Fecha Fin", "Motivo", "Turno", "Grupo"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jLabel5.setText("Motivo");

        jLabel6.setText("Turno");

        jLabel7.setText("Grupo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtGrupo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTurno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtCI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      //Acá nos preguntamos si hay alguna cajita,a la que no se le ingreso datos,
     //con el método isEmpty,que devuelve un true si la caja esta vacia.
 if (txtCI.getText().isEmpty() || txtFechaInicio.getText().isEmpty() || txtFechaFin.getText().isEmpty()|| txtMotivo.getText().isEmpty()|| txtTurno.getText().isEmpty()||txtGrupo.getText ().isEmpty ())  {
            JOptionPane.showMessageDialog(null, "Estos datos no pueden estar vacíos");
        } else {
//En el caso que las cajitas no esten vacias,creamos una instancia del objeto.
//Para guardarlo con sus respectivos atributos            
            InasistenciaDocente per = new InasistenciaDocente();

            try {
               
                per.setCi(txtCI.getText());
                per.setFecha_in(txtFechaInicio.getText());
                per.setFecha_fin(txtFechaFin.getText());
                per.setMotivo(txtMotivo.getText());
                per.setTurno(txtTurno.getText());
                per.setGrupo(txtGrupo.getText());
              
//Llamamos a la clase fachada,para que se comunique con la de persistencia y guarde el objeto.
                fachadaper.guardarInasistencia(per);
//Ventana de diálogo que le aprece el usuario,donde le brinda información.nada más.
                JOptionPane.showMessageDialog(this, "Datos Guardados correctamente");

            }catch (Exception ex) {

                JOptionPane.showMessageDialog(this, ex.getMessage());
                JOptionPane.showMessageDialog(this, "No se pudo guardar tus datos");

            }
//Logger.getLogger(Personaje.class.getName()): Aquí se obtiene una instancia del 
//Logger asociado con la clase Persona. Logger es una clase proporcionada por el paquete java.util.logging 
//que se utiliza para registrar mensajes de registro..log(Level.SEVERE, null, ex): Llama al método log 
//de la instancia del Logger. Este método se utiliza para registrar un mensaje de registro. Los parámetros 
//que recibe son:Level.SEVERE: Especifica el nivel de gravedad del mensaje de registro. En este caso, SEVERE 
//indica un problema grave o un error.Esta línea de código está registrando un mensaje de error grave 
//asociado con la excepción ex en el registro de eventos a través del Logger asociado con la clase Persona.


        }

      
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
                String ci = txtCI.getText().trim();
    if (ci.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese una CI.");
        return;
    }

    try {
        // Llama a tu fachada: public Persona busquedaPorCi(String ci)
        InasistenciaDocente p = fachadaper.busquedaPorCi(ci);

        // Rellena campos 
        txtFechaInicio.setText(p.getFecha_in());
        txtFechaFin.setText(p.getFecha_fin());
        txtMotivo.setText(p.getMotivo());
        txtTurno.setText(p.getTurno());
        txtGrupo.setText(p.getGrupo());

        // Muestra en la tabla
        modeloTabla.setRowCount(0);
        modeloTabla.addRow(new Object[]{ p.getCi(), p.getCi(), p.getFecha_in(),p.getFecha_fin(),p.getMotivo(),p.getTurno(),p.getGrupo()  });

    } catch (PersonaException pe) {
        // NO ENCONTRADA u otro error de dominio
        limpiarCamposYTabla();
        JOptionPane.showMessageDialog(this, pe.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);

    } catch (SQLException se) {
        // Error técnico de BD
        limpiarCamposYTabla();
        JOptionPane.showMessageDialog(this, "Error de base de datos. Revise la conexión o los permisos.",
                "Error", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(getClass().getName()).log(Level.SEVERE, "SQLException en busquedaPorCi", se);

    } catch (Exception ex) {
        limpiarCamposYTabla();
        JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado.",
                "Error", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Error general en busquedaPorCi", ex);
    }

//Acá vamos capturando posibles excepciones por capas,primero la capa de más de arriba la clase del perosnaje
//Luego vamos a la capa de manejos de excepciones,en este caso de la base de datos,donde se encuentra la 
//conexion.Y por último chequeamos en las clases propias que ofrece java,al estar trabajando con los 
//servidores de MySQL.
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        InasistenciaDocente perso = new InasistenciaDocente();
                perso.setCi(txtCI.getText());
        if (txtCI.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la cedula para eliminar el personaje");
        } else {
            try {
                
                String ci= txtCI.getText();

                fachadaper.eliminarIansistencia(ci);

                JOptionPane.showMessageDialog(this, "Datos eliminados correctamente");
            } catch (Exception ex) {
                Logger.getLogger(PersonaException.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtTareas1;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
